### ISSUE TITLE
通过链接访问杨宝页面得到nginx404错误

### ISSUE THREAD

**Issue by Luxcoldury** [MIMONATCH/xuyanshe-voice-button#36]
通过链接[https://xysbtn.xiaoblogs.cn/yangbao](https://xysbtn.xiaoblogs.cn/yangbao)直接访问杨宝页面会得到nginx的404错误，但通过其他页面nav栏跳转可以正常访问。疑似nginx配置```location```处未添加```yangbao```？

**Comment by MIMONATCH** [comment]
已解决，忘记配置了
